use_frameworks!

target 'readingWindow_Example' do
  pod 'readingWindow', :path => '../'

  target 'readingWindow_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
